Update Envoy to e4992b9 (Oct 09, 2023)
envoyproxy/nighthawk pull request #1027
Opened 2023-10-09 16:26 UTC by qqustc

- no code changes

2023-10-11 20:59 UTC, qqustc commented
/retest

2023-10-11 21:00 UTC, qqustc commented
\retest

2023-10-11 23:32 UTC, mum4k requested changes

2023-10-11 23:32 UTC, mum4k commented on tools/code_format/config.yaml
> +- source/extensions/resource_monitors/downstream_connections/BUILD
Is this change necessary? I think this is one of the files we are keeping "in sync" with Envoy and they don't seem to be including `downstream_connections` here.

2023-10-11 23:32 UTC, mum4k commented on test/integration/configurations/nighthawk_15_listeners_http_origin.yaml
> +        max_active_downstream_connections: 100000
How did we choose the value `100000` ? We should add a comment here and in the other files to explain our choice and its significance to the posterity.

Same question about the chosen `refresh_interval`.

2023-10-12 16:41 UTC, mum4k commented
Obsoleted by #1028

2023-10-12 16:41 UTC, closed without merging