Sink: add in memory sink, slightly refactor validation/testing.
envoyproxy/nighthawk pull request #657
Opened 2021-03-20 21:57 UTC by oschaaf

- Adds an in-memory sink. Comes in handy in tests, and could serve
  a future role if we want to converge the way results are handled
  in both distributed and non-distributed tests.
- Slightly refactors validation & testing to make it easier to see
  what is specific to FileSinkImpl, making things a little more
  natural in case someone else wants to  add a new sink type in the
  future.
- Avoid MOCK_METHOD_N in the Sink mock as per recommendation.

Signed-off-by: Otto van der Schaaf <ovanders@redhat.com>

2021-03-22 19:09 UTC, mum4k commented
@jiajunye please review and assign back to me once done.

2021-03-22 20:35 UTC, jiajunye commented
LGTM

2021-03-23 02:16 UTC, mum4k requested changes

2021-03-23 02:16 UTC, mum4k commented on source/sink/sink_impl.cc
> +absl::Status validateKey(absl::string_view key, const bool validate_as_directory_name) {
(nit) Is it important for the bool argument to be const?

2021-03-23 02:16 UTC, mum4k commented on source/sink/sink_impl.cc
> +  return absl::Status();
I think the more conventional way of returning OK is:

```cc
return absl::OkStatus();
```

This one also works, but requires the reader to understand that an empty status defaults to OK.

https://abseil.io/blog/2020-091021-status

2021-03-23 02:16 UTC, mum4k commented on source/sink/sink_impl.cc
> +  return absl::Status(absl::StatusCode::kNotFound, "Not found");
(optional, fyi) Similarly to the comment above, a shorter version is:

```cc
return absl::NotFoundError("...");
```

Feel free to ignore, I know we have a few of these already in.

2021-03-23 02:16 UTC, mum4k commented on source/sink/sink_impl.cc
> +  return absl::Status(absl::StatusCode::kNotFound, "Not found");
Can we expand the error message, giving a better idea as to what wasn't found? Seeing an error message like this one might not be very helpful when debugging.

2021-03-23 07:57 UTC, oschaaf commented
Thanks for the review @mum4k , comments addressed in 135e803b

2021-03-23 18:59 UTC, mum4k approved these changes

2021-03-23 18:59 UTC, merged