Change signature for createUserDefinedOutputPlugin to allow validation and prevent unnecessary casting
envoyproxy/nighthawk pull request #942
Opened 2022-11-11 20:23 UTC by dubious90

Originally we were under a mistaken impression that this function had to have a specific signature, but we actually have full control over it.  Removing the unnecessary dynamic_cast from all of the functions, and allowing absl::StatusOr for up front config validation.

This PR also modifies the users of these methods to use the validation appropriately.

2022-11-11 20:48 UTC, dubious90 commented
@qqustc please review and assign to @mum4k when done.

2022-11-15 06:15 UTC, qqustc submitted a review, later dismissed

2022-11-15 13:06 UTC, mum4k requested changes

2022-11-15 13:06 UTC, mum4k commented on source/user_defined_output/log_response_headers_plugin.cc
> +  Envoy::MessageUtil::unpackTo(message, config);
Would `MessageUtil::unpackToNoThrow` be a better match now, since it returns status instead of throwing?

2022-11-15 13:06 UTC, mum4k commented on source/user_defined_output/user_defined_output_plugin_creator.cc
> +    ;
Looks like this is an extra `;`.

2022-11-16 16:50 UTC, mum4k approved these changes

2022-11-16 16:50 UTC, merged