Allow disabling default failure predicates.
envoyproxy/nighthawk pull request #997
Opened 2023-06-07 15:52 UTC by mergeconflict

Works on #826

2023-06-07 16:29 UTC, mum4k requested changes
Looks like the CI failed, because README needs to be regenerated.

Could you try running this locally and uploading the commit?

```
tools/update_cli_readme_documentation.sh --mode fix
```

Additionally we should add both a unit test and an e2e test for the new feature. The unit test should live [here](https://github.com/envoyproxy/nighthawk/blob/main/test/options_test.cc) and the integration test probably [here](https://github.com/envoyproxy/nighthawk/blob/main/test/integration/test_integration_basics.py).

2023-06-07 20:43 UTC, mergeconflict commented
> Could you try running this locally and uploading the commit?
> 
> ```
> tools/update_cli_readme_documentation.sh --mode fix
> ```

Done, thanks!

> Additionally we should add both a unit test and an e2e test for the new feature. The unit test should live [here](https://github.com/envoyproxy/nighthawk/blob/main/test/options_test.cc) and the integration test probably [here](https://github.com/envoyproxy/nighthawk/blob/main/test/integration/test_integration_basics.py).

I've added a unit test. I agree an e2e test would make sense, but I'm having some trouble constructing one, maybe you have some advice... My issue is that I can't find a way to configure NH test server to send error responses, which is necessary to verify that there aren't any failure predicates. Any suggestion?

2023-06-07 20:51 UTC, mum4k commented
Without looking closer - could we achieve the same by pointing Nighthawk to a port the test server **isn't** listening on?

2023-06-08 20:26 UTC, mum4k requested changes
Looks great, glad this approach worked out. I have two minor requests aiming to make the integration test case more understandable.

2023-06-09 19:34 UTC, mergeconflict commented on test/integration/test_integration_basics.py
> +  root_uri = re.sub(":[0-9]+", ":123", http_test_server_fixture.getTestServerRootUri())
Done

2023-06-09 19:34 UTC, mergeconflict commented on test/integration/test_integration_basics.py
> +      "--no-default-failure-predicates"
Done, I updated the docstring to be a bit more explicit.

2023-06-12 00:52 UTC, mum4k reviewed
Looks good, thank you for moving the code to the utility library.

Looks like the CI is failing due to formatting of Python files, could you execute `ci/do_ci.sh fix_format` and see if that helps?

2023-06-12 20:36 UTC, mum4k approved these changes
Thank you @mergeconflict !

2023-06-12 20:36 UTC, merged